theme: jekyll-theme-cayman
title: >
        <div>
          <img src="/media/headshot.JPG" alt="Nikhil Soni" width="15%" height="15%" style="border:9px solid #326B83;border-radius:50%;vertical-align:middle;box-shadow:1.5px 1.5px 5px #000000;">
          <span style="">NIKHIL SONI</span>
        </div>
description: >
              Graduate Student, School of Industrial Engineering  <br>
              <a href="mailto:sonin@purdue.edu" style="color:white">Mail</a> | <a href="https://www.linkedin.com/in/soninikhil" style="color:white">LinkedIn</a> <br>
              <img src="/media/purdue_logo.svg" alt="Purdue University" width="12.5%" height="12.5%">
github:
  is_project_page: false
google_analytics: UA-123727784-1