theme: jekyll-theme-cayman
title: >
        <div>
          <img src="media/headshot.JPG" alt="Nikhil Soni" width="15%" height="15%" style="border:9px solid #326B83;border-radius:50%;vertical-align:middle;box-shadow:1.5px 1.5px 5px #000000;">
          <span style="">NIKHIL SONI</span>
        </div>
description: >
              Graduate Student, School of Industrial Engineering  <br>
              <img src="https://www.purdue.edu/purdue/images/logo.svg" alt="Purdue University" width="12.5%" height="12.5%">
google_analytics: UA-123727784-1